# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='recipient_type',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
