# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_recipient_recipient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='recipient_text',
            new_name='recipient_name',
        ),
        migrations.AddField(
            model_name='recipient',
            name='recipient_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
